// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://frczskpfacpeyndgrhcm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZyY3pza3BmYWNwZXluZGdyaGNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5Mjg3ODEsImV4cCI6MjA2NjUwNDc4MX0.CQ7kqHaYhu-1nzVlN3afiB03Zii66GuT_-r4jfDKM7U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});